import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import {Quicksand } from 'next/font/google'
import "./globals.css";

const quicksand = Quicksand({
  variable: "--font-quicksand-sans",
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Conexão Mel",
  description: "Generated by create Conexão Mel",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={quicksand.className}>
        {children}
      </body>
    </html>
  );
}
