import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import {Quicksand } from 'next/font/google'
import "./globals.css";
import { Toaster } from "sonner";
import { EditProvider } from "@/providers/edit";
import Script from "next/script";


const quicksand = Quicksand({
  variable: "--font-quicksand-sans",
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Conexão Mel",
  description: "Generated by create Conexão Mel",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <EditProvider>
        <body className={quicksand.className}>
          {children}
          <Toaster 
            position="bottom-right"
            toastOptions={{ 
              style:{
                backgroundColor: "#FFB64CAD",
                color: "#f1f1f1",
                borderColor: "rgba(255, 255, 255, 0.5)"
              }}
            }
          />
          {/* Chatling scripts */}
          <Script
            id="chatling-config"
            strategy="beforeInteractive"
            dangerouslySetInnerHTML={{
              __html: `window.chtlConfig = { chatbotId: "1892961315" };`,
            }}
          />
          <Script
            id="chatling-script"
            strategy="lazyOnload"
            async
            src="https://chatling.ai/js/embed.js"
          />
        </body>
      </EditProvider>
    </html>
  );
}
